language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'
 
env:
  - SYMFONY_DEPRECATIONS_HELPER=disabled

before_script:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit  -c phpunit.xml.dist --coverage-clover=coverage.clover

notifications:
    email: false

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
